"""add root_folder_id to users

Revision ID: 0b946b9bd345
Revises: 28f8ac607127
Create Date: 2026-01-30 04:37:28.656124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b946b9bd345'
down_revision = '28f8ac607127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'folders', ['root_folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('root_folder_id')

    # ### end Alembic commands ###
