"""initial schema

Revision ID: 1086f60d82cd
Revises: 
Create Date: 2025-12-22 10:18:29.591789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1086f60d82cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_info',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folder_info.folder_id'], ),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_table('file_info',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('remaining_space', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('delete_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder_info.folder_id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('file_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_info')
    op.drop_table('folder_info')
    # ### end Alembic commands ###
